apiVersion: ebs.aws.edenlab.io/v1alpha1
kind: EBSSnapshotRestore
metadata:
  labels:
    app.kubernetes.io/name: ebs-snapshot-restore
    app.kubernetes.io/managed-by: kustomize
  name: ebs-snapshot-restore
spec:
  restorePlans:
    db-ebs-csi-snapshot:
      clusters:
        - name: db-cluster-0
          type: statefulset
          replicas: 1
          namespace: db
          pvcStorageClass: gp3-restore
          parallelPodManagement: true
          skipWaitScaleUp: true
          claimSelector:
            matchLabels:
              release: db

      hooks:
        preHook:
          events:
            - pre-restore
          command: ["bash", "-c"]
          args:
            - |
              set -e
              echo "Hello"
          image: "ubuntu"
          extraSecrets:
            - name: db-cluster-secret

        postHook:
          events:
            - post-restore
          command: ["bash", "-c"]
          args:
            - |
              set -e
              env | grep "DB_CREDENTIALS"
          image: "ubuntu"
          mutable: true
          extraSecrets:
            - name: db-cluster-secret
              prefix: DB_CREDENTIALS

        execHook:
          events:
            - post-restore
          command: ["bash", "-c"]
          args:
            - |
              set -e
              kubectl exec -n db $(kubectl get pods -n db -l release=db -o jsonpath='{.items[0].metadata.name}') -- echo "hello from pod"
          image: "bitnami/kubectl"
          privileges:
            podExec: true

        nodeHook:
          events:
            - post-restore
          command: ["bash", "-c"]
          args:
            - |
              set -e
              fio --filename=/dev/nvme1n1 --rw=read --bs=128k --iodepth=63 \
                  --numjobs=8 --ioengine=io_uring --direct=1 --name=warmup
          image: "ubuntu"
          privileges:
            nodeAccess:
              nodeSelector:
                matchLabels:
                  node-role: db-node

      operators:
        - name: operator
          replicas: 1
          namespace: db
          type: deployment

      snapshotRestoreTime: "202601010000"

    object-storage-ebs-csi-snapshot:
      clusters:
        - name: object-storage
          type: statefulset
          replicas: 4
          namespace: object-storage
          skipWaitScaleDown: true
          skipRestoringPVCs:
            - export-1-object-storage-3
          claimSelector:
            matchLabels:
              release: object-storage

      snapshotRestoreTime: "202601010000"
