//go:build !ignore_autogenerated

/*
Copyright 2026 Edenlab.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapReference) DeepCopyInto(out *ConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapReference.
func (in *ConfigMapReference) DeepCopy() *ConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRestore) DeepCopyInto(out *EBSSnapshotRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRestore.
func (in *EBSSnapshotRestore) DeepCopy() *EBSSnapshotRestore {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRestoreList) DeepCopyInto(out *EBSSnapshotRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EBSSnapshotRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRestoreList.
func (in *EBSSnapshotRestoreList) DeepCopy() *EBSSnapshotRestoreList {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRestoreSpec) DeepCopyInto(out *EBSSnapshotRestoreSpec) {
	*out = *in
	if in.RestorePlans != nil {
		in, out := &in.RestorePlans, &out.RestorePlans
		*out = make(map[string]RestorePlan, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRestoreSpec.
func (in *EBSSnapshotRestoreSpec) DeepCopy() *EBSSnapshotRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRestoreStatus) DeepCopyInto(out *EBSSnapshotRestoreStatus) {
	*out = *in
	if in.RestorePlans != nil {
		in, out := &in.RestorePlans, &out.RestorePlans
		*out = make(map[string]RestorePlanStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRestoreStatus.
func (in *EBSSnapshotRestoreStatus) DeepCopy() *EBSSnapshotRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraSecretRef) DeepCopyInto(out *ExtraSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraSecretRef.
func (in *ExtraSecretRef) DeepCopy() *ExtraSecretRef {
	if in == nil {
		return nil
	}
	out := new(ExtraSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookPrivileges) DeepCopyInto(out *HookPrivileges) {
	*out = *in
	if in.NodeAccess != nil {
		in, out := &in.NodeAccess, &out.NodeAccess
		*out = new(NodeAccessPrivilege)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookPrivileges.
func (in *HookPrivileges) DeepCopy() *HookPrivileges {
	if in == nil {
		return nil
	}
	out := new(HookPrivileges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookSettings) DeepCopyInto(out *HookSettings) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraSecrets != nil {
		in, out := &in.ExtraSecrets, &out.ExtraSecrets
		*out = make([]ExtraSecretRef, len(*in))
		copy(*out, *in)
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = new(HookPrivileges)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookSettings.
func (in *HookSettings) DeepCopy() *HookSettings {
	if in == nil {
		return nil
	}
	out := new(HookSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAccessPrivilege) DeepCopyInto(out *NodeAccessPrivilege) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAccessPrivilege.
func (in *NodeAccessPrivilege) DeepCopy() *NodeAccessPrivilege {
	if in == nil {
		return nil
	}
	out := new(NodeAccessPrivilege)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreHookStatus) DeepCopyInto(out *RestoreHookStatus) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreHookStatus.
func (in *RestoreHookStatus) DeepCopy() *RestoreHookStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreHookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePlan) DeepCopyInto(out *RestorePlan) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]RestoreTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]RestoreTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make(map[string]*HookSettings, len(*in))
		for key, val := range *in {
			var outVal *HookSettings
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(HookSettings)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePlan.
func (in *RestorePlan) DeepCopy() *RestorePlan {
	if in == nil {
		return nil
	}
	out := new(RestorePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePlanStatus) DeepCopyInto(out *RestorePlanStatus) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]RestoreTargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]RestoreTargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make([]RestoreHookStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePlanStatus.
func (in *RestorePlanStatus) DeepCopy() *RestorePlanStatus {
	if in == nil {
		return nil
	}
	out := new(RestorePlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSnapshotRef) DeepCopyInto(out *RestoreSnapshotRef) {
	*out = *in
	if in.PVCStorageClass != nil {
		in, out := &in.PVCStorageClass, &out.PVCStorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSnapshotRef.
func (in *RestoreSnapshotRef) DeepCopy() *RestoreSnapshotRef {
	if in == nil {
		return nil
	}
	out := new(RestoreSnapshotRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTarget) DeepCopyInto(out *RestoreTarget) {
	*out = *in
	if in.SkipRestoringPVCs != nil {
		in, out := &in.SkipRestoringPVCs, &out.SkipRestoringPVCs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PVCStorageClass != nil {
		in, out := &in.PVCStorageClass, &out.PVCStorageClass
		*out = new(string)
		**out = **in
	}
	if in.ClaimSelector != nil {
		in, out := &in.ClaimSelector, &out.ClaimSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTarget.
func (in *RestoreTarget) DeepCopy() *RestoreTarget {
	if in == nil {
		return nil
	}
	out := new(RestoreTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreTargetStatus) DeepCopyInto(out *RestoreTargetStatus) {
	*out = *in
	if in.SnapshotsRef != nil {
		in, out := &in.SnapshotsRef, &out.SnapshotsRef
		*out = make([]RestoreSnapshotRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreTargetStatus.
func (in *RestoreTargetStatus) DeepCopy() *RestoreTargetStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreTargetStatus)
	in.DeepCopyInto(out)
	return out
}
